### ISSUE TITLE
Main Menu

### ISSUE THREAD

**Issue by marwaboukarim** [giorgiouboldi/IPS-design#1]
When the main menu slides open, it leaves a light purple margin on the right and on the bottom, with a small whit gap in the bottom right corner which gives a bit of a strange visual effect. Maybe it could be solved by removing the light purple margin from the page and have them menu open "on top" of the page.

<img width="497" alt="Screenshot 2020-05-06 at 16 34 07" src="https://user-images.githubusercontent.com/64909873/81189955-81577100-8fb7-11ea-869a-0c7f02d40a77.png">

**Comment by marwaboukarim** [comment]
When the user is in one section, maybe it can be highlighted just by changing the color of the text to red instead of having a blue background behind it.
<img width="429" alt="Screenshot 2020-05-07 at 10 58 30" src="https://user-images.githubusercontent.com/64909873/81275363-da73e300-9051-11ea-96de-a2d4a5efe54d.png">

**Comment by Mai-tbaileh** [comment]
for the first comment .The bug was because of the horizontal and vertical scroll bar.I removed the horizontal scroll bar (according to other bug in this list of bugs).So I think now it is ok .Please check .

**Comment by Mai-tbaileh** [comment]
second comment done
