### ISSUE TITLE
Empty State Search

### ISSUE THREAD

**Issue by marwaboukarim** [giorgiouboldi/IPS-design#11]
It might be nice to have a message saying "There are no results for your search"... or something like that so that the user doesn't just see a blank area with no feedback.

**Comment by Mai-tbaileh** [comment]
this message need to be added to all explorers 
I add it like this can you provide me with suitable design for it.
![test5](https://user-images.githubusercontent.com/48549937/81820108-db68b100-9538-11ea-96be-230bca61730e.PNG)

**Comment by giorgiouboldi** [comment]
That's good ;) Feel free to close the issue
