### ISSUE TITLE
In-page sub-menus styling

### ISSUE THREAD

**Issue by marwaboukarim** [giorgiouboldi/IPS-design#16]
The dividers should be the same color #E3E1DC and aligned on the left and right.

The behaviour of the sub-menu links have a few issues at the moment:
1. On hover, the dividers should not be affected, at the moment the bottom divider is being pushed down.
2. The section the user is on, so the "selected" link should have an purple underline overlapping with the divider (example below)
<img width="1188" alt="Screenshot 2020-05-07 at 11 17 12" src="https://user-images.githubusercontent.com/64909873/81277169-54a56700-9054-11ea-8da8-c9bba76dbd17.png">

3. Hover effect of the link should be same as the above just changing the color of the text and underline to red
4. The focus state of the link can simply be the same as the hover effect. Right now there is a gray background forming around the text (screenshot from website below)
<img width="490" alt="Screenshot 2020-05-07 at 11 16 32" src="https://user-images.githubusercontent.com/64909873/81277201-5ff89280-9054-11ea-89d3-77914dd60c26.png">

**Comment by Mai-tbaileh** [comment]
Done
