### ISSUE TITLE
Tab Styling 

### ISSUE THREAD

**Issue by marwaboukarim** [giorgiouboldi/IPS-design#18]
The tabs in the About -> Governance should be aligned to the left with the rest of the content and the behaviour can be like the image attached. No hover state necessary for the already selected tab.
<img width="656" alt="Screenshot 2020-05-07 at 11 52 02" src="https://user-images.githubusercontent.com/64909873/81280893-705f3c00-9059-11ea-9abe-5b34753b7801.png">

**Comment by Mai-tbaileh** [comment]
done
