### ISSUE TITLE
System fonts

### ISSUE THREAD

**Issue by marwaboukarim** [giorgiouboldi/IPS-design#19]
The font for number of events found, location, and the label "Speakers" looks like it has been replaced by a system font.
<img width="885" alt="Screenshot 2020-05-07 at 12 14 08" src="https://user-images.githubusercontent.com/64909873/81283195-88848a80-905c-11ea-95c4-aa2b8f7e651f.png">
<img width="785" alt="Screenshot 2020-05-07 at 12 18 55" src="https://user-images.githubusercontent.com/64909873/81283462-f9c43d80-905c-11ea-981f-d51fb82ea7a4.png">

**Comment by Mai-tbaileh** [comment]
The event explorer and the unpcoming events both slides not available for clicking to find the correct fonts.Could you please provide me with the right fonts for them.

for the number of events "I can identify the font"but i notice that the font of number is different from the Events label please check the image below

![test4](https://user-images.githubusercontent.com/48549937/81818070-38169c80-9536-11ea-9e88-87cc4f5708ad.PNG)


I apply the font from the mookup to the label and below is the result
![test5](https://user-images.githubusercontent.com/48549937/81818361-9c396080-9536-11ea-8552-975c562316dc.PNG)

Is this right???It is not like the mookup

When the font is Fedra Sans Std Normal so It is Fedra Sans Arabic Book right??

**Comment by giorgiouboldi** [comment]
yes it's Fedra Sans Arabic Book
