### ISSUE TITLE
Font Styles Journals

### ISSUE THREAD

**Issue by marwaboukarim** [giorgiouboldi/IPS-design#21]
The font style on the volume and date should be Fedra Sans Book 12 as per the initial design https://projects.invisionapp.com/d/main/default/#/console/16984241/356047881/preview

The font style in Journal explorer:
Name of the journal should be in Fedra Sans Normal 14 and the label "From the editor" in Fedra Sans Book Italic 14
<img width="283" alt="Screenshot 2020-05-07 at 14 59 26" src="https://user-images.githubusercontent.com/64909873/81297485-98f42f80-9073-11ea-8420-d25d9d75293a.png">

Same for Mobile

**Comment by Mai-tbaileh** [comment]
the journal explorer page , the css of the article is not available so i guess the fonts.
Even the issue "volume and year" I think its font is wrong.
For the "From the editor" label i put the font that you mentioned  the Fedra Sans Book Italic 14
but it is not working.

The italic is only for Fedra Serif ,there is no fedra sans italic.

the image below when i put the fonts you mentioned and please tell me the name of the journal 
having the right font now?
![test1](https://user-images.githubusercontent.com/48549937/81810825-537caa00-952c-11ea-9416-7db63940a0d9.PNG)


![test2](https://user-images.githubusercontent.com/48549937/81810970-8d4db080-952c-11ea-8361-a660e4496db5.PNG)
![test3](https://user-images.githubusercontent.com/48549937/81810973-8de64700-952c-11ea-8655-9cb1da316e19.PNG)

**Comment by giorgiouboldi** [comment]
I see it correctly now. The only details is the label English that is in Arial. Maybe we can make it like everyywhere else (see screenshot)

<img width="138" alt="Screenshot 2020-05-21 at 11 24 36" src="https://user-images.githubusercontent.com/2106518/82544662-c05bf980-9b55-11ea-8a49-7003457c204a.png">

**Comment by Mai-tbaileh** [comment]
your previous comment is related to the carousel in the home page right??For the english label 
The font is 
font-family: "Fedra Sans Arabic Book",Arial,Helvetica,sans-serif;

is this wrong??
