### ISSUE TITLE
Header Mobile

### ISSUE THREAD

**Issue by marwaboukarim** [giorgiouboldi/IPS-design#23]
The logo seems a bit small and so does the menu icon and the "menu" label (which could even be removed altogether.

**Comment by Mai-tbaileh** [comment]
it will be great if you provide me with a svg files for the menu in english and arabic for mobiles 
for the menu and the close button.
so i can enlarge the file

**Comment by giorgiouboldi** [comment]
I think for mobile we can proceed without the labels. here is the menu icon without label https://projects.invisionapp.com/d/main?origin=v7#/projects/prototypes/16984241/assets/755282076?folderID=349117322
