### ISSUE TITLE
Menu Mobile

### ISSUE THREAD

**Issue by marwaboukarim** [giorgiouboldi/IPS-design#24]
When the menu is open, there is a strange white line that cuts through the top. Also here the "close" label is not necessary, but if you want to keep it, I think the font is used at the moment isn't Fedra. The scrolling of the menu goes in both directions but it should just be vertical.
It seems there is a space after the words "Journals", "Books", "Events" and "blogs" so they are misaligned to the center.

**Comment by Mai-tbaileh** [comment]
the close icon "with the label close" all together is a svg file so it would be great if you create a svg file without the label.

For the line this is from the design .but the original design has the close icon without the label so it was better.

**Comment by Mai-tbaileh** [comment]
the horizontal scroll and the space after some menu items as resolved.

**Comment by giorgiouboldi** [comment]
Cool! Here is the icon without the label https://projects.invisionapp.com/d/main?origin=v7#/projects/prototypes/16984241/assets/755278622?folderID=349117322
