### ISSUE TITLE
Arabic Text Styles

### ISSUE THREAD

**Issue by marwaboukarim** [giorgiouboldi/IPS-design#30]
- There is no Fedra Arabic Italic style, so it is being replaced by the system font in a forced Italic. In Arabic, the weight should remain the same as the corresponding text in English but the Italic should be removed.
- Letter spacing should be removed for all Arabic text styles as it creates unwanted divisions between the letters (namely h5, links and tags)
<img width="1207" alt="Screenshot 2020-05-07 at 17 14 33" src="https://user-images.githubusercontent.com/64909873/81312094-820b0880-9086-11ea-823a-5aa5fc587ea4.png">
<img width="152" alt="Screenshot 2020-05-07 at 17 14 44" src="https://user-images.githubusercontent.com/64909873/81312110-89321680-9086-11ea-94a7-814345abd163.png">

**Comment by Mai-tbaileh** [comment]
Done.
