### ISSUE TITLE
Design UI for Live streaming

### ISSUE THREAD

**Issue by giorgiouboldi** [giorgiouboldi/IPS-design#31]

**Comment by giorgiouboldi** [comment]
https://projects.invisionapp.com/share/7SR00UYJ3GB#/screens/420538549 - the little red dot could blink to be more visible. What do you think?

**Comment by Mai-tbaileh** [comment]
yes you are right

**Comment by Mai-tbaileh** [comment]
gorgio i implement this option .But on ipad and iphone i try to do options so you can choose from them or give me other solution.

![live-ipad](https://user-images.githubusercontent.com/48549937/84239075-a6825680-ab04-11ea-8076-2eed790cb202.JPG)


![live -phone](https://user-images.githubusercontent.com/48549937/84239082-aa15dd80-ab04-11ea-92e4-6424d3af8414.JPG)
![live -phone(option2)](https://user-images.githubusercontent.com/48549937/84239092-ada96480-ab04-11ea-86ba-20bdbe9db592.JPG)
![live -phone(option3)](https://user-images.githubusercontent.com/48549937/84239100-b00bbe80-ab04-11ea-9e5c-95fc85d502b8.JPG)

**Comment by giorgiouboldi** [comment]
What about this for all mobile devices?
https://projects.invisionapp.com/d/main?origin=v7#/console/16984241/421779191/preview?scrollOffset=12353

**Comment by Mai-tbaileh** [comment]
perfect . I will use it for mobile.

For tablets??
