### ISSUE TITLE
Cover images are stretched on large screens

### ISSUE THREAD

**Issue by giorgiouboldi** [giorgiouboldi/IPS-design#37]
![Screenshot 2020-06-16 at 17 29 05](https://user-images.githubusercontent.com/2106518/84794773-f37b9680-aff6-11ea-939c-b8618f832ef9.png)

**Comment by Mai-tbaileh** [comment]
we faced this problem of square image this photo is 799 X 533  and  the size is 57kb 
so the image is not of high resolution and after cropping it stretched,is there a way to avoid stretching the images in this case???


so based on your experience shall I put a requirements for images dimensions and size??

**Comment by giorgiouboldi** [comment]
@Mai-tbaileh  sorry I didn't see the reply. I would suggest to use css property "object-fit: cover;" see [documentation ](https://www.w3schools.com/css/css3_object-fit.asp)
