### ISSUE TITLE
Typography hierarchy 

### ISSUE THREAD

**Issue by marwaboukarim** [giorgiouboldi/IPS-design#9]
In the "Our Journals" section, the date should be in a different text style -> Fedra Sans Book 14
(reference of initial design attached here too)
<img width="376" alt="Screenshot 2020-05-06 at 17 33 49" src="https://user-images.githubusercontent.com/64909873/81196901-eadb7d80-8fbf-11ea-983f-b17c3386e24a.png">

**Comment by Mai-tbaileh** [comment]
done but i feel that it is different than the mookups.
please [check the link of the page]([check](https://www.palestine-studies.org/en/journals))
https://www.palestine-studies.org/en/journals

the first image from mookup 
![mookup](https://user-images.githubusercontent.com/48549937/82499055-a55b9c00-9af9-11ea-8a4c-f1275b42b722.PNG)

the second one after fixing the bug
![Capture22](https://user-images.githubusercontent.com/48549937/82499077-b2788b00-9af9-11ea-9a98-897f81ceef21.PNG)

**Comment by giorgiouboldi** [comment]
It's fine for me as it is now. Feel free to close the issue

**Comment by Mai-tbaileh** [comment]
> done but i feel that it is different than the mookups.
> please check the link of the page
> https://www.palestine-studies.org/en/journals
> 
> the first image from mookup
> ![mookup](https://user-images.githubusercontent.com/48549937/82499055-a55b9c00-9af9-11ea-8a4c-f1275b42b722.PNG)
> 
> the second one after fixing the bug
> ![Capture22](https://user-images.githubusercontent.com/48549937/82499077-b2788b00-9af9-11ea-9a98-897f81ceef21.PNG)
